// STATUS CODES CONSTANTS
export const STATUS_OK_SUCCESS_CODE = 200;
export const CREATED_SUCCESS_CODE = 201;
export const ACCEPTED_CODE = 202;
export const NO_CONTENT_CODE = 204;

export const BAD_REQUEST_ERROR_CODE = 400;
export const UNAUTHORIZED_ERROR_CODE = 401;
export const FORBIDDEN_ERROR_CODE = 403;
export const NOT_FOUND_ERROR_CODE = 404;
export const CONFLICT_ERROR_CODE = 409;
export const UNPROCESSABLE_ENTITY_CODE = 422;

export const INTERNAL_SERVER_ERROR_CODE = 500;
export const NOT_IMPLEMENTED_CODE = 501;
export const BAD_GATEWAY_CODE = 502;
export const SERVICE_UNAVAILABLE_CODE = 503;
export const GATEWAY_TIMEOUT_CODE = 504;
